#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
INTERVAL=${INTERVAL}
DETECTION_MODE=${DETECTION_MODE}
LOG_LEVEL=${LOG_LEVEL}
APPRISE=${APPRISE}
CF_USER=${CF_USER}
CF_APIKEY=$(mask "${CF_APIKEY}")
CF_APITOKEN=$(mask "${CF_APITOKEN}")
CF_HOSTS=${CF_HOSTS}
CF_RECORDTYPES=${CF_RECORDTYPES}
----------------------------------------------------------------------
"
