#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
TAG=${TAG}
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
INTERVAL=${INTERVAL}
DETECTION_MODE=${DETECTION_MODE}
LOG_LEVEL=${LOG_LEVEL}
CF_USER=${CF_USER}
CF_APIKEY=${CF_APIKEY}
CF_ZONES=${CF_ZONES}
CF_HOSTS=${CF_HOSTS}
CF_RECORDTYPES=${CF_RECORDTYPES}
INFLUXDB_ENABLED=${INFLUXDB_ENABLED}
INFLUXDB_HOST=${INFLUXDB_HOST}
INFLUXDB_DB=${INFLUXDB_DB}
INFLUXDB_USER=${INFLUXDB_USER}
INFLUXDB_PASS=${INFLUXDB_PASS}
----------------------------------------------------------------------
"

groupmod -o -g "${PGID}" hotio
usermod -o -u "${PUID}" hotio
