#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "PATH=/usr/bin:/bin:/usr/local/bin" > /etc/cron.d/crontab
echo "${CRON_TIME} hotio /app/cloudflare-ddns.sh" >> /etc/cron.d/crontab
chmod 644 /etc/cron.d/crontab
chmod 755 /app/cloudflare-ddns.sh
